# Site settings
title: Rashid Shaikh
email: contact@rashids.in
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer, Agile Practitioner and Technology Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rashids.in" # the base hostname & protocol for your site
twitter_username: rashid_shaikh15
github_username:  rshaikh

# Build settings
markdown: kramdown
